spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/datas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
        ddl-auto: update
  data:
    redis:
      host: "localhost"
      port: 6379